#Jersey client settings
jerseyClient:
    #The maximum idle time for a connection, once established.
    timeout: 512ms
    #The size of the work queue of the pool used for asynchronous requests.
    #Additional threads will be spawn only if the queue is reached its maximum size.
    workQueueSize: 16

goEuroApi: http://api.goeuro.com/api/v2/position/suggest/en/

version: 0.0.1

server:
  applicationConnectors:
  - type: http
    port: 9900
  adminConnectors:
  - type: http
    port: 9901


